/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import borse.Acoes;
import borse.Ficheiro;
import borse.Investidor;
import borse.MyDate;
import borse.Obrigações;
import borse.Oferta;
import borse.Warrants;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class AddTitulos extends javax.swing.JPanel {

    /**
     * Creates new form ListarClientes
     */
    //DefaultListModel lista = new DefaultListModel();
    DefaultComboBoxModel lista = new DefaultComboBoxModel();
    DefaultComboBoxModel lista2 = new DefaultComboBoxModel();
    Investidor user = new Investidor();
    public AddTitulos(Investidor user ) {
        initComponents();
        this.user = user;
        Acoes ti = new Acoes();
        for (Acoes ac : Ficheiro.getRepositorio().getAcao().values()) {
            lista.addElement(ac.getSigla());
        }
        this.jComboBox1.setModel(lista);
        
        for (Investidor ac : Ficheiro.getRepositorio().getInv().values()) {
            lista2.addElement(ac.getNome());
            
        }
        this.jCBuser.setModel(lista2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdicionar = new javax.swing.JButton();
        jLabelSpi = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextPreco = new javax.swing.JTextField();
        jTextQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLAdicionarTitulo = new javax.swing.JLabel();
        jLImagem = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCBuser = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");

        jLabel2.setText("Preço:");

        jLabel3.setText("Ação:");

        jTextPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPrecoFocusLost(evt);
            }
        });

        jTextQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextQtdFocusLost(evt);
            }
        });
        jTextQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQtdActionPerformed(evt);
            }
        });

        jLabel4.setText("Ordem:");

        jLAdicionarTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLAdicionarTitulo.setText("Adicionar Título");

        jLImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionarTitulo.png"))); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("User:");

        jLabel6.setText("Dinheiro: ");

        jButton2.setText("Aumentar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton3)
                        .addGap(87, 87, 87)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLImagem)
                        .addGap(87, 87, 87)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAdicionar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(57, 57, 57)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCBuser, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLAdicionarTitulo))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabelSpi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 625, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLAdicionarTitulo)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCBuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLImagem)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addGap(38, 38, 38)
                .addComponent(jLabelSpi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed

        Acoes aac = new Acoes();
        
        Investidor add = new Investidor();
        add = Ficheiro.getRepositorio().getInv().get(this.jCBuser.getSelectedItem().toString());
        
        
        if (add.getCarteira().getAcoes().containsKey(this.jComboBox1.getSelectedItem().toString())) {
            aac = add.getCarteira().getAcoes().get(this.jComboBox1.getSelectedItem().toString());
            aac.setSigla(this.jComboBox1.getSelectedItem().toString());
            aac.setPreco(Float.parseFloat(this.jTextPreco.getText()));
            aac.setQta(aac.getQta() + Integer.parseInt(this.jTextQtd.getText()));
            JOptionPane.showMessageDialog(null, "Título adicionado com sucesso");
        } else {
            String nome = Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString()).getNome();
            aac.setQta(Integer.parseInt(this.jTextQtd.getText()));
            aac.setSigla(this.jComboBox1.getSelectedItem().toString());
            aac.setPreco(Float.parseFloat(this.jTextPreco.getText()));
            aac.setQta(Integer.parseInt(this.jTextQtd.getText()));
            aac.setNome(nome);
            add.getCarteira().getAcoes().put(aac.getSigla(), aac);
            JOptionPane.showMessageDialog(null, "Título adicionado com sucesso");
        }
        
        Oferta x = new Oferta(add, Integer.parseInt(this.jTextQtd.getText()), 0, aac, 0);
        add.getCarteira().getHistorico().put(x, 6);


    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        /*Acoes ti = new Acoes();

        if (Ficheiro.getRepositorio().getAcao() != null) {
            if (Ficheiro.getRepositorio().getAcao().containsKey(this.jComboBox1.getSelectedItem().toString())) {
                ti = Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString());
                this.jTextArea1.setText("Nome: " + ti.getNome() + "\nPreço: " + ti.getPreco() + "\nQta: " + ti.getQta() + "\nSigla: " + ti.getSigla());
            }
        }*/
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQtdActionPerformed

    private void jTextPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPrecoFocusLost
        this.calcularValor();
    }//GEN-LAST:event_jTextPrecoFocusLost

    private void jTextQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextQtdFocusLost
        this.calcularValor();
    }//GEN-LAST:event_jTextQtdFocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MyDate x = new MyDate(Ficheiro.getData().getAno() + 1, 1, 21);
        Ficheiro.getData().setAno(Ficheiro.getData().getAno() + 1);
        Obrigações y = new Obrigações();
        y.verifica(user);
        Warrants v = new Warrants();
        v.verifica(user);
        System.out.println("verifica " + Ficheiro.getData().getAno());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Investidor add = new Investidor();
        add = Ficheiro.getRepositorio().getInv().get(this.jCBuser.getSelectedItem().toString());
        add.getCarteira().setSaldo(add.getCarteira().getSaldo() + Float.parseFloat(this.jTextField1.getText()));
        Oferta x = new Oferta();
        x.setPreco(Float.parseFloat(this.jTextField1.getText()));
       
        add.getCarteira().getHistorico().put(x, 5);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void calcularValor() {
        int qta;
        float valor;
        System.out.println("ola");
        try {
            qta = Integer.parseInt(this.jTextQtd.getText());
        } catch (NumberFormatException ex) {
            qta = 0;
            System.out.println("erro: " + ex);
        }

        try {
            valor = Float.parseFloat(this.jTextPreco.getText());
        } catch (NumberFormatException ex) {
            valor = 0;
            System.out.println("erro: " + ex);
        }

        valor *= qta;

        this.jLabelValor.setText(Float.toString(valor));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JComboBox<String> jCBuser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLAdicionarTitulo;
    private javax.swing.JLabel jLImagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSpi;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextPreco;
    private javax.swing.JTextField jTextQtd;
    // End of variables declaration//GEN-END:variables
}
