package GUI;

import borse.Ficheiro;
import borse.Investidor;
import borse.MyDate;
import borse.Warrants;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel Gonçalves
 */
public class BemVindo extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form BemVindo
     */
    private JPanel painelVisivel;
    Investidor user = new Investidor();

    public BemVindo() {
        initComponents();
        setSize(800, 600);
        Ficheiro.setData(new MyDate());
        jBRegistar.setBackground(new Color(0, 0, 0, 0));
        this.painelVisivel = this.jPanelInicial;
        Ficheiro.desserializar("te");
        /*Warrants x = new Warrants();
        x.verifica(user);*/
        this.jMenuBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jPanelInicial = new javax.swing.JPanel();
        jBRegistar = new javax.swing.JButton();
        jLLogin = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        jLPassword = new javax.swing.JLabel();
        jPFPassword = new javax.swing.JPasswordField();
        jBEntrar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIAdicionarTitulos = new javax.swing.JMenuItem();
        jMISave = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMICriarAções = new javax.swing.JMenuItem();
        jMIComprar = new javax.swing.JMenuItem();
        jMIVenderAções = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jBRegistar.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBRegistar.setText("REGISTAR");
        jBRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistarActionPerformed(evt);
            }
        });

        jLLogin.setText("Login");

        jLPassword.setText("Password");

        jBEntrar1.setText("Entrar");
        jBEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrar1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/registo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBEntrar1)
                            .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLPassword)
                                .addComponent(jLLogin)
                                .addComponent(jTFLogin)
                                .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRegistar)
                .addGap(47, 47, 47))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addComponent(jLLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEntrar1)))
                .addGap(70, 70, 70)
                .addComponent(jLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jBRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMIAdicionarTitulos.setText("Adicionar Títulos");
        jMIAdicionarTitulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAdicionarTitulosActionPerformed(evt);
            }
        });
        jMenu1.add(jMIAdicionarTitulos);

        jMISave.setText("Save");
        jMISave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMISave);

        jMenuItem11.setText("Registar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ações");

        jMICriarAções.setText("Criar Ações");
        jMICriarAções.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICriarAçõesActionPerformed(evt);
            }
        });
        jMenu2.add(jMICriarAções);

        jMIComprar.setText("Comprar Ações");
        jMIComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIComprarActionPerformed(evt);
            }
        });
        jMenu2.add(jMIComprar);

        jMIVenderAções.setText("Vender Ações");
        jMIVenderAções.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVenderAçõesActionPerformed(evt);
            }
        });
        jMenu2.add(jMIVenderAções);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Warrants");

        jMenuItem4.setText("Criar Warrants");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem2.setText("Comprar Warrants");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem5.setText("Vender Warrants");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Obrigações");

        jMenuItem7.setText("Criar Obrigações");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Comprar Obrigações");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Vender Obrigações");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("User");

        jMenuItem10.setText("Início");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem3.setText("Listar Carteira");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem1.setText("Historico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void loginBack() {
        this.painelVisivel = this.jPanelInicial;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }
    
    private void jBRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistarActionPerformed
        // TODO add your handling code here:
        Registo panelRegisto = new Registo(null);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelRegisto;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jBRegistarActionPerformed

    private void jMIComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIComprarActionPerformed

        ComprarTitulos panelBuy = new ComprarTitulos(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelBuy;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();

    }//GEN-LAST:event_jMIComprarActionPerformed

    private void jMICriarAçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICriarAçõesActionPerformed
        CriarAcoes panelAc = new CriarAcoes();
        this.painelVisivel.setVisible(false);
        painelVisivel = panelAc;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMICriarAçõesActionPerformed

    private void jMIAdicionarTitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAdicionarTitulosActionPerformed
        AddTitulos panelAdd = new AddTitulos(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelAdd;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMIAdicionarTitulosActionPerformed

    private void jMIVenderAçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVenderAçõesActionPerformed
        VenderTitulos panelSell = new VenderTitulos(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelSell;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMIVenderAçõesActionPerformed

    private void jBEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrar1ActionPerformed
        

        Investidor a = new Investidor();
        if (Ficheiro.getRepositorio().getInv().containsKey(this.jTFLogin.getText())) {
            a = Ficheiro.getRepositorio().getInv().get(this.jTFLogin.getText());
            System.out.println("dajiusodpok");
            if (a.getPassword().equals(this.jPFPassword.getText())) {
                user = a;
                if(!user.isAdmin()) {
                    this.jMICriarAções.setVisible(false);
                    this.jMIAdicionarTitulos.setVisible(false);
                    this.jMenuItem4.setVisible(false);
                    this.jMenuItem11.setVisible(false);
                    this.jMenuItem7.setVisible(false);
                }
                JOptionPane.showMessageDialog(null, "Logado!");
                Menu panelMenu = new Menu(user);
                this.jMenuBar1.setVisible(true);
                painelVisivel = panelMenu;
                this.setContentPane(painelVisivel);
                painelVisivel.setVisible(true);
                this.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "Password Errada!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "User não existe");
        }
    }//GEN-LAST:event_jBEntrar1ActionPerformed

    private void jMISaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISaveActionPerformed
        // TODO add your handling code here:
        Ficheiro.serializar("te");
    }//GEN-LAST:event_jMISaveActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListarHistorico panelHist = new ListarHistorico(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelHist;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ComprarWarrants buyW = new ComprarWarrants(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = buyW;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ListarCarteira listar = new ListarCarteira(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = listar;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CriarWarrants war = new CriarWarrants(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = war;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        VenderWarrants war = new VenderWarrants(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = war;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CriarObrigações panelOb = new CriarObrigações(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelOb;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        ComprarObrigações panelCompOb = new ComprarObrigações(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelCompOb;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        VenderObrigações panelVenderOb = new VenderObrigações(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = panelVenderOb;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = menu;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Registo reg = new Registo(user);
        this.painelVisivel.setVisible(false);
        painelVisivel = reg;
        this.setContentPane(painelVisivel);
        painelVisivel.setVisible(true);
        this.repaint();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    @Override
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BemVindo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEntrar1;
    private javax.swing.JButton jBRegistar;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMIAdicionarTitulos;
    private javax.swing.JMenuItem jMIComprar;
    private javax.swing.JMenuItem jMICriarAções;
    private javax.swing.JMenuItem jMISave;
    private javax.swing.JMenuItem jMIVenderAções;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JTextField jTFLogin;
    // End of variables declaration//GEN-END:variables
}
