/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import borse.Acoes;
import borse.Ficheiro;
import borse.Investidor;
import borse.Oferta;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class ComprarTitulos extends javax.swing.JPanel {

    /**
     * Creates new form ListarClientes
     */
    //DefaultListModel lista = new DefaultListModel();
    DefaultComboBoxModel lista = new DefaultComboBoxModel();
    Investidor user = new Investidor();
    float val;

    public ComprarTitulos(Investidor user) {
        initComponents();
        Acoes ti = new Acoes();
        this.user = user;
        for (Acoes aac : Ficheiro.getRepositorio().getAcao().values()) {
            lista.addElement(aac.getSigla());
            this.jComboBox1.setModel(lista);
        }

        val = user.getCarteira().getSaldo() - user.getCarteira().getSaldoInvestido();

        if (this.jComboBox1.getItemCount() > 0) {
            if (Ficheiro.getRepositorio().getAcao().containsKey(this.jComboBox1.getSelectedItem().toString())) {
                ti = Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString());
                this.jTextArea1.setText("DinheiroD: " + val + "  DinheiroA: " + user.getCarteira().getSaldo() + "\nNome: " + ti.getNome() + "\nPreço: " + ti.getPreco()  + "\nSigla: " + ti.getSigla());
            }
        }

        this.jLabel5.setVisible(false);
        this.jTextTrigger.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonComprar = new javax.swing.JButton();
        jLabelSpi = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextPreco = new javax.swing.JTextField();
        jTextQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLComprarAção = new javax.swing.JLabel();
        jLImagem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextTrigger = new javax.swing.JTextField();
        jRBbuy = new javax.swing.JRadioButton();

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonComprar.setText("Comprar");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade:");

        jLabel2.setText("Preço:");

        jLabel3.setText("Ação:");

        jTextPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPrecoFocusLost(evt);
            }
        });

        jTextQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextQtdFocusLost(evt);
            }
        });
        jTextQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQtdActionPerformed(evt);
            }
        });

        jLabel4.setText("Ordem:");

        jRadioButton1.setText("Start");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        jRadioButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRadioButton1FocusLost(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLComprarAção.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLComprarAção.setText("Comprar Ação");

        jLImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Money.png"))); // NOI18N

        jLabel5.setText("Trigger:");

        jRBbuy.setText("Comprar já");
        jRBbuy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRBbuyItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabelSpi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLImagem)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLComprarAção)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRBbuy)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jTextQtd)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(50, 50, 50)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addComponent(jTextTrigger))))
                                .addComponent(jButtonComprar, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jLComprarAção)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLImagem)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton1)
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jRBbuy)
                .addGap(18, 18, 18)
                .addComponent(jButtonComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSpi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        Acoes ti = new Acoes();
        float val1;
        float val;

        val = user.getCarteira().getSaldo() - user.getCarteira().getSaldoInvestido();
        float valor = this.calcularValor();

        if (valor <= val) {
            if (jTextTrigger.getText().isEmpty()) {
                val1 = 0;
            } else {
                val1 = Float.parseFloat(jTextTrigger.getText());
            }

            user.getCarteira().setSaldoInvestido(user.getCarteira().getSaldoInvestido() + valor);
            ti = Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString());
            user.getCarteira().getHistorico().put(new Oferta(user, Integer.parseInt(this.jTextQtd.getText()), Float.parseFloat(this.jTextPreco.getText()), ti), 1);
            ti.criarOfertaCompra(user, Integer.parseInt(this.jTextQtd.getText()), Float.parseFloat(this.jTextPreco.getText()), ti, this.jRadioButton1.isSelected(), val1, true);
            JOptionPane.showMessageDialog(null, "Compra efetuada!");
        } else {
            System.out.println("e o dinheiro?");
            JOptionPane.showMessageDialog(null, "Não tem dinheiro suficiente!");
            
        }

    }//GEN-LAST:event_jButtonComprarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        Acoes ti = new Acoes();

        if (Ficheiro.getRepositorio().getAcao().containsKey(this.jComboBox1.getSelectedItem().toString())) {
            ti = Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString());
            this.jTextArea1.setText("DinheiroD: " + val + "  DinheiroA: " + user.getCarteira().getSaldo() + "\nNome: " + ti.getNome() + "\nPreço: " + ti.getPreco()  + "\nSigla: " + ti.getSigla());

        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQtdActionPerformed

    private void jTextPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPrecoFocusLost
        this.calcularValor();
    }//GEN-LAST:event_jTextPrecoFocusLost

    private void jTextQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextQtdFocusLost
        this.calcularValor();
    }//GEN-LAST:event_jTextQtdFocusLost

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton1FocusLost

    }//GEN-LAST:event_jRadioButton1FocusLost

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        // TODO add your handling code here:
        if (this.jRadioButton1.isSelected()) {
            this.jLabel5.setVisible(true);
            this.jTextTrigger.setVisible(true);
        } else {
            this.jLabel5.setVisible(false);
            this.jTextTrigger.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRBbuyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRBbuyItemStateChanged
        if (this.jRBbuy.isSelected() && !Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString()).getOfertaVenda().isEmpty()) {
            String x = String.valueOf(Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString()).getOfertaVenda().peek().getPreco());
            
            this.jTextPreco.setText(x);
            int qtd = Integer.parseInt(this.jTextQtd.getText());
            if (qtd > Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString()).getOfertaVenda().peek().getQuantidade()) {
               // JOptionPane.showMessageDialog(null, "Quantidade excedida");
                this.jTextQtd.setText(String.valueOf(Ficheiro.getRepositorio().getAcao().get(this.jComboBox1.getSelectedItem().toString()).getOfertaVenda().peek().getQuantidade()));
            }
            this.jTextQtd.setEnabled(false);
            this.jTextPreco.setEnabled(false);

        } else {
            this.jTextQtd.setEnabled(true);
            this.jTextPreco.setEnabled(true);
            this.jRBbuy.setSelected(false);
        }
    }//GEN-LAST:event_jRBbuyItemStateChanged

    private float calcularValor() {
        int qta;
        float valor;
        System.out.println("ola");
        try {
            qta = Integer.parseInt(this.jTextQtd.getText());
        } catch (NumberFormatException ex) {
            qta = 0;
            System.out.println("erro: " + ex);
        }

        try {
            valor = Float.parseFloat(this.jTextPreco.getText());
        } catch (NumberFormatException ex) {
            valor = 0;
            System.out.println("erro: " + ex);
        }

        valor *= qta;

        this.jLabelValor.setText(Float.toString(valor));
        return valor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLComprarAção;
    private javax.swing.JLabel jLImagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelSpi;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JRadioButton jRBbuy;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextPreco;
    private javax.swing.JTextField jTextQtd;
    private javax.swing.JTextField jTextTrigger;
    // End of variables declaration//GEN-END:variables
}
