/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import borse.Ficheiro;
import borse.Investidor;
import borse.MyDate;
import borse.Obrigações;
import borse.Oferta;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Gonçalves
 */
public class CriarObrigações extends javax.swing.JPanel {

    Investidor user = new Investidor();
    
    public CriarObrigações(Investidor user) {
        initComponents();
        this.user = user;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCriar = new javax.swing.JButton();
        jLPreço = new javax.swing.JLabel();
        jTFValorNominal = new javax.swing.JTextField();
        jLTaxa = new javax.swing.JLabel();
        jTFTaxa = new javax.swing.JTextField();
        jLNome = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLSigla = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jLQuantidade = new javax.swing.JLabel();
        jTFSigla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jBCriar.setText("Criar");
        jBCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCriarActionPerformed(evt);
            }
        });

        jLPreço.setText("Valor");

        jLTaxa.setText("Taxa");

        jLNome.setText("Nome");

        jLSigla.setText("Sigla");

        jLQuantidade.setText("Quantidade");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Criar Obrigação");

        jLabel2.setText("Data Pagamento");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_garantia.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(585, 585, 585)
                        .addComponent(jBCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLQuantidade)
                                    .addComponent(jLPreço)
                                    .addComponent(jLNome)
                                    .addComponent(jLSigla)
                                    .addComponent(jLTaxa)
                                    .addComponent(jLabel2))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(jTFTaxa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNome)
                                    .addComponent(jTFSigla, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFValorNominal, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel1))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSigla)
                            .addComponent(jTFSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPreço)
                            .addComponent(jTFValorNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTaxa)
                            .addComponent(jTFTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLQuantidade)
                            .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jBCriar)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCriarActionPerformed
       Obrigações ob = new Obrigações();
       SimpleDateFormat sd = new SimpleDateFormat("dd");
        String dia = sd.format(this.jDateChooser1.getDate());
        System.out.println(dia);
        MyDate a = new MyDate(this.jDateChooser1.getDate().getYear() + 1900, this.jDateChooser1.getDate().getMonth() + 1, Integer.parseInt(dia));
        ob.setDtfinal(a);
        System.out.println(a.getData());
        ob.setNome(this.jTFNome.getText());
        ob.setSigla(this.jTFSigla.getText()+ "-" +(this.jTFTaxa.getText())+ "-" + ob.getInfoFinal());
        ob.setPreco(Float.parseFloat(this.jTFValorNominal.getText()));
        ob.setTaxaJuro(Float.parseFloat(this.jTFTaxa.getText()));
        ob.setQta(Integer.parseInt(this.jTFQuantidade.getText()));
        if (Ficheiro.getRepositorio().getObrigações().containsKey(ob.getSigla())) {
            Ficheiro.getRepositorio().getObrigações().get(ob.getSigla()).criarOfertaVenda(user, ob, ob.getQta(), ob.getPreco());
        }
        else {
            Ficheiro.getRepositorio().getObrigações().put(ob.getSigla(), ob);
            ob.criarOfertaVenda(user, ob, ob.getQta(), ob.getPreco());
        }
        
        user.getCarteira().getHistorico().put(new Oferta(user, ob, ob.getQta(), ob.getPreco()) , 10);
        JOptionPane.showMessageDialog(null, "Obrigação criada com sucesso");
    }//GEN-LAST:event_jBCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCriar;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPreço;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLSigla;
    private javax.swing.JLabel jLTaxa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFQuantidade;
    private javax.swing.JTextField jTFSigla;
    private javax.swing.JTextField jTFTaxa;
    private javax.swing.JTextField jTFValorNominal;
    // End of variables declaration//GEN-END:variables
}
