/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import borse.Acoes;
import borse.Ficheiro;
import borse.Investidor;
import borse.MyDate;
import borse.Oferta;
import borse.Warrants;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CriarWarrants extends javax.swing.JPanel {

    /**
     * Creates new form CriarWarrants
     */
    DefaultComboBoxModel lista = new DefaultComboBoxModel();
    Investidor user = new Investidor();

    public CriarWarrants(Investidor user) {
        initComponents();
        for (Acoes aac : Ficheiro.getRepositorio().getAcao().values()) {
            lista.addElement(aac.getSigla());
        }
        user = user;
        this.jCBSigla.setModel(lista);
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBSigla = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTFNome = new javax.swing.JTextField();
        jRBC = new javax.swing.JRadioButton();
        jRBP = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTFPreçoE = new javax.swing.JTextField();
        jTFPreçoW = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFQtd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jRBC.setText("Call");
        jRBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCActionPerformed(evt);
            }
        });

        jRBP.setText("Put");
        jRBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPActionPerformed(evt);
            }
        });

        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTFPreçoW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPreçoWActionPerformed(evt);
            }
        });

        jLabel1.setText("Preço do Exercício");

        jLabel2.setText("Preço do Warrant: ");

        jLabel3.setText("Nome:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Ação:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Criar Warrant");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/warrant.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFPreçoE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFNome)
                                    .addComponent(jTFQtd)
                                    .addComponent(jTFPreçoW)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBC)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBP))
                                    .addComponent(jCBSigla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFPreçoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFPreçoW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBC)
                            .addComponent(jRBP)))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBCActionPerformed

    private void jRBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Warrants x = new Warrants();
        Warrants d = new Warrants();
        char p = 'P';
        boolean c = false;
        SimpleDateFormat sd = new SimpleDateFormat("dd");
        String dia = sd.format(this.jDateChooser1.getDate());
        System.out.println(dia);
        MyDate a = new MyDate(this.jDateChooser1.getDate().getYear() + 1900, this.jDateChooser1.getDate().getMonth() + 1, Integer.parseInt(dia));
        x.setValidade(a);
        if (this.jRBC.isSelected()) {
            p = 'C';
        }
        else {
            p = 'P';
        }
        x.setNome(this.jTFNome.getText());
        x.setPreçoE(Float.parseFloat(this.jTFPreçoE.getText()));
        x.setPreco(Float.parseFloat(this.jTFPreçoW.getText()));
        x.setQta(Integer.parseInt(this.jTFQtd.getText()));
        x.setSigla(this.jCBSigla.getSelectedItem().toString() + "-" + x.getInfo() + "-" + p + "-" + x.getPreçoE());
        x.setAc(Ficheiro.getRepositorio().getAcao().get(this.jCBSigla.getSelectedItem().toString()));
        if (p == 'C') {
            c = true;
            System.out.println("tru");
        } else {
            c = false;
            System.out.println("false");
        }
        x.setCall(c);
        System.out.println(x.isCall());
              
        System.out.println("nome: " + user.getNome());
        if (Ficheiro.getRepositorio().getWarrants().containsKey(x.getSigla())) {
            Ficheiro.getRepositorio().getWarrants().get(x.getSigla()).criarOfertaVenda(user, x, x.getQta(), x.getPreco(), x.getAc());
        } else {
            Ficheiro.getRepositorio().getWarrants().put(x.getSigla(), x);
            x.criarOfertaVenda(user, x, x.getQta(), x.getPreco(), x.getAc());
        }
    
        user.getCarteira().getHistorico().put(new Oferta(user, x, x.getQta(), x.getPreco(), null) , 7);
        JOptionPane.showMessageDialog(null, "Warrant criado com sucesso");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTFPreçoWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPreçoWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPreçoWActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBSigla;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRBC;
    private javax.swing.JRadioButton jRBP;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPreçoE;
    private javax.swing.JTextField jTFPreçoW;
    private javax.swing.JTextField jTFQtd;
    // End of variables declaration//GEN-END:variables
}
