/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import borse.Investidor;
import borse.Oferta;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ListarHistorico extends javax.swing.JPanel {

    /**
     * Creates new form ListarOfertas
     */
    Investidor user = new Investidor();

    public ListarHistorico(Investidor user) {
        initComponents();
        DefaultTableModel model=(DefaultTableModel) jTTabela.getModel();
        
       this.user = user;
        
        System.out.println("começa");
        System.out.println(user.getCarteira().getHistorico().values());  

        for (Oferta i : user.getCarteira().getHistorico().keySet()) {

            switch (user.getCarteira().getHistorico().get(i)) {
                case 1:
                    //this.jTextArea1.setText( "\nEnviou a Compra de: " + i.getQuantidade() + " ação " + i.getAcao().getSigla() + " ao preço de " + i.getPreco() + this.jTextArea1.getText());
                    model.addRow(new Object[]{"[Ações]Enviou a Compra",i.getAcao().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 2:
//                    this.jTextArea1.setText( "\nEnviou a Venda de: " + i.getQuantidade() + " ação " + i.getAcao().getSigla() + " ao preço de " + i.getPreco() + this.jTextArea1.getText());
                    model.addRow(new Object[]{"[Ações]Enviou a Venda",i.getAcao().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 3:
                    //this.jTextArea1.setText( "\n>>Efetuada a Compra de: " + i.getQuantidade() + " ação " + i.getAcao().getSigla() + " ao preço de " + i.getPreco() + this.jTextArea1.getText());
                    model.addRow(new Object[]{"[Ações]Efetuada a Compra",i.getAcao().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 4:
                    //this.jTextArea1.setText("\n>>Efetuada a Venda de: " + i.getQuantidade() + " ação " + i.getAcao().getSigla() + " ao preço de " + i.getPreco() + this.jTextArea1.getText());
                    model.addRow(new Object[]{"[Ações]Efetuou a Venda",i.getAcao().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 5:
                    model.addRow(new Object[]{"Aumento Capital", "-","-",i.getPreco(),"-"});
                    break;
                case 6: 
                    model.addRow(new Object[]{"[Ações]Aumento Títulos",i.getAcao().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 7:
                    model.addRow(new Object[]{"[Warrants]Enviou a Venda",i.getWarrant().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 8:
                    model.addRow(new Object[]{"[Warrants]Efetuada A Compra",i.getWarrant().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 9:
                    model.addRow(new Object[]{"[Warrants]Efetuada a Venda",i.getWarrant().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 10:
                    model.addRow(new Object[]{"[Obrigações]Enviou a Venda",i.getObrigação().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 11: 
                    model.addRow(new Object[]{"[Obrigações]Efetuada A Compra",i.getObrigação().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                case 12:
                    model.addRow(new Object[]{"[Obrigações]Efetuada a Venda",i.getObrigação().getSigla(),i.getQuantidade(),i.getPreco(),i.getPreco()*i.getQuantidade()});
                    break;
                    
            }
        }
                
                
                
            
   
        
     
       

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTTabela = new javax.swing.JTable();

        jTTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Sigla", "Quantidade", "Preço Unitário", "Preço Total"
            }
        ));
        jScrollPane2.setViewportView(jTTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTTabela;
    // End of variables declaration//GEN-END:variables
}
