/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import borse.Investidor;
import borse.Acoes;
import borse.Obrigações;
import borse.Warrants;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Daniel Gonçalves
 */
public class ListarCarteira extends javax.swing.JPanel {

    Investidor user = new Investidor();
    
    public ListarCarteira(Investidor user) {
        initComponents();
        DefaultTableModel model=(DefaultTableModel) jTTabela.getModel();
        this.user = user;
        for (Acoes aac : user.getCarteira().getAcoes().values()) {
            if(aac.getQta() > 0)
                model.addRow(new Object[]{aac.getSigla(), aac.getNome(), aac.getPreco(), aac.getQta()});
        }
        System.out.println(user.getCarteira().getLW().keySet());
        for (Warrants aac : user.getCarteira().getLW().values()) {
         if(aac.getQta() > 0)
                model.addRow(new Object[]{aac.getSigla(), aac.getNome(), aac.getPreco(), aac.getQta()});
        }
        
        for (Obrigações aac : user.getCarteira().getObg().values()) {
         if(aac.getQta() > 0)
                model.addRow(new Object[]{aac.getSigla(), aac.getNome(), aac.getPreco(), aac.getQta()});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabela = new javax.swing.JTable();
        jLTitulosCarteira = new javax.swing.JLabel();

        jTTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sigla", "Nome", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTTabela);

        jLTitulosCarteira.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLTitulosCarteira.setText("Títulos em Carteira");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLTitulosCarteira)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLTitulosCarteira)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLTitulosCarteira;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTTabela;
    // End of variables declaration//GEN-END:variables
}
