/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import borse.Acoes;
import borse.Ficheiro;
import borse.Investidor;
import borse.MyDate;
import borse.Oferta;
import borse.Warrants;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class VenderWarrants extends javax.swing.JPanel {

    /**
     * Creates new form VenderWarrants
     */
    Investidor user = new Investidor();
    DefaultComboBoxModel lista = new DefaultComboBoxModel();

    public VenderWarrants(Investidor user) {
        initComponents();
        this.user = user;
        for (Warrants aac : user.getCarteira().getLW().values()) {
            if(aac.getQta() > 0)
            lista.addElement(aac.getSigla());
        }

        this.jComboBox1.setModel(lista);
        Warrants ti = new Warrants();

        if (this.jComboBox1.getItemCount() > 0) {
            if (user.getCarteira().getLW().containsKey(this.jComboBox1.getSelectedItem().toString())) {
                ti = user.getCarteira().getLW().get(this.jComboBox1.getSelectedItem().toString());
                this.jTextArea1.setText("Nome: " + ti.getNome() + "\nPreço: " + ti.getPreco() + "\nQtaD: " + ti.getQta() + "\nSigla: " + ti.getSigla());

            } else {
                System.out.println("not foun");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTFPreçoW = new javax.swing.JTextField();
        jTFQtd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("Vender");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Preço do Warrant:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Warrant");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Vender Warrant");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/venderwarrant.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFPreçoW, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTFPreçoW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTFQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(240, 240, 240))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Warrants x = new Warrants();
        Warrants d = new Warrants();
        System.out.println("here" + user.getCarteira().getLW().keySet());
        int qtd;
        float preco;
        System.out.println(this.jComboBox1.getSelectedItem().toString());
        System.out.println(user.getCarteira().getLW().get(this.jComboBox1.getSelectedItem().toString()));
        if (user.getCarteira().getLW().get(this.jComboBox1.getSelectedItem().toString()).getQta() >= Integer.parseInt(this.jTFQtd.getText())) {
            x.setPreco(Float.parseFloat(this.jTFPreçoW.getText()));
            x.setQta(Integer.parseInt(this.jTFQtd.getText()));
            if (Ficheiro.getRepositorio().getWarrants().containsKey(this.jComboBox1.getSelectedItem().toString())) {
                d = Ficheiro.getRepositorio().getWarrants().get(this.jComboBox1.getSelectedItem().toString());
                qtd = x.getQta();
                preco = x.getPreco();
                user.getCarteira().getHistorico().put(new Oferta(user, d, qtd, preco, null) , 7);
                
                Ficheiro.getRepositorio().getWarrants().get(this.jComboBox1.getSelectedItem().toString()).criarOfertaVenda(user, d, x.getQta(), x.getPreco(), d.getAc());
                user.getCarteira().getLW().get(this.jComboBox1.getSelectedItem().toString()).setQta(user.getCarteira().getLW().get(this.jComboBox1.getSelectedItem().toString()).getQta()  - Integer.parseInt(this.jTFQtd.getText()));
            JOptionPane.showMessageDialog(null, "Warrant inserida no mercado com sucesso");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Não tens quantidade suficiente!");

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPreçoW;
    private javax.swing.JTextField jTFQtd;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
