/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import borse.Ficheiro;
import borse.Investidor;
import borse.Obrigações;
import borse.Oferta;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Gonçalves
 */
public class VenderObrigações extends javax.swing.JPanel {

    Investidor user = new Investidor();
    DefaultComboBoxModel lista = new DefaultComboBoxModel();
    public VenderObrigações(Investidor user) {
        initComponents();
        this.user = user;
        for (Obrigações aac : user.getCarteira().getObg().values()) {
            if(aac.getQta() > 0)
            lista.addElement(aac.getSigla());
        }
        this.jComboBox1.setModel(lista);
        Obrigações ti = new Obrigações();
        
          if (this.jComboBox1.getItemCount() > 0) {
            if (user.getCarteira().getObg().containsKey(this.jComboBox1.getSelectedItem().toString())) {
                ti = user.getCarteira().getObg().get(this.jComboBox1.getSelectedItem().toString());
                this.jTextArea1.setText("Nome: " + ti.getNome() + "\nPreço: " + ti.getPreco() + "\nQtaD: " + ti.getQta() + "\nSigla: " + ti.getSigla() + "\nTaxa de Juros: " + ti.getTaxaJuro());

            } else {
                System.out.println("not foun");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTFPreço = new javax.swing.JTextField();
        jLPreco = new javax.swing.JLabel();
        jLQuantidade = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jBVender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLPreco.setText("Preço");

        jLQuantidade.setText("Quantidade");

        jBVender.setText("Vender");
        jBVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVenderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Vender Obrigação");

        jLabel2.setText("Obrigação");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vender.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLQuantidade)
                            .addGap(18, 18, 18)
                            .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLPreco)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel1))
                    .addComponent(jBVender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLPreco)
                                            .addComponent(jTFPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLQuantidade))
                                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jBVender))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jBVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVenderActionPerformed
        Obrigações x = new Obrigações();
        Obrigações d = new Obrigações();
        
        System.out.println("here" + user.getCarteira().getObg().keySet());
       
        System.out.println(this.jComboBox1.getSelectedItem().toString());
        System.out.println(user.getCarteira().getObg().get(this.jComboBox1.getSelectedItem().toString()));
        if (user.getCarteira().getObg().get(this.jComboBox1.getSelectedItem().toString()).getQta() >= Integer.parseInt(this.jTFQuantidade.getText())) {
            x.setPreco(Float.parseFloat(this.jTFPreço.getText()));
            x.setQta(Integer.parseInt(this.jTFQuantidade.getText()));
            if (Ficheiro.getRepositorio().getObrigações().containsKey(this.jComboBox1.getSelectedItem().toString())) {
                d = Ficheiro.getRepositorio().getObrigações().get(this.jComboBox1.getSelectedItem().toString());
                Ficheiro.getRepositorio().getObrigações().get(this.jComboBox1.getSelectedItem().toString()).criarOfertaVenda(user, d, x.getQta(), x.getPreco());
                user.getCarteira().getObg().get(this.jComboBox1.getSelectedItem().toString()).setQta(user.getCarteira().getObg().get(this.jComboBox1.getSelectedItem().toString()).getQta()  - Integer.parseInt(this.jTFQuantidade.getText()));
                System.out.println(d.getOfertaVenda());
                
                    
            }
            JOptionPane.showMessageDialog(null, "Obrigação inserida no mercado com sucesso");
        }
        
        else
            JOptionPane.showMessageDialog(null, "Não tens quantidade suficiente!");
    }//GEN-LAST:event_jBVenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBVender;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLPreco;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPreço;
    private javax.swing.JTextField jTFQuantidade;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
